"""reading and user database optimizations

Revision ID: 583d7a32b69d
Revises: b2032e2f2ca1
Create Date: 2024-01-17 09:34:08.591131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583d7a32b69d'
down_revision: Union[str, None] = 'b2032e2f2ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('hexagram_stationary', sa.Integer(), nullable=False))
    op.add_column('readings', sa.Column('hexagram_moving', sa.Integer(), nullable=True))
    op.alter_column('readings', 'reader_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('readings', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('readings', 'topic',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('readings', 'reading_notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('readings', 'hexagram_primary')
    op.drop_column('readings', 'line_moving_2')
    op.drop_column('readings', 'hexagram_secondary')
    op.drop_column('readings', 'line_moving_6')
    op.drop_column('readings', 'line_moving_1')
    op.drop_column('readings', 'line_moving_3')
    op.drop_column('readings', 'line_moving_5')
    op.drop_column('readings', 'line_moving_4')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('readings', sa.Column('line_moving_4', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('readings', sa.Column('line_moving_5', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('readings', sa.Column('line_moving_3', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('readings', sa.Column('line_moving_1', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('readings', sa.Column('line_moving_6', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('readings', sa.Column('hexagram_secondary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('readings', sa.Column('line_moving_2', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('readings', sa.Column('hexagram_primary', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('readings', 'reading_notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('readings', 'topic',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('readings', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('readings', 'reader_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('readings', 'hexagram_moving')
    op.drop_column('readings', 'hexagram_stationary')
    # ### end Alembic commands ###
