"""readings table

Revision ID: 84bd18ea4322
Revises: 
Create Date: 2023-12-08 11:31:51.448881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84bd18ea4322'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('reading_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('hexagram_primary', sa.Integer(), nullable=False),
    sa.Column('hexagram_secondary', sa.Integer(), nullable=True),
    sa.Column('line_moving_1', sa.Boolean(), nullable=False),
    sa.Column('line_moving_2', sa.Boolean(), nullable=False),
    sa.Column('line_moving_3', sa.Boolean(), nullable=False),
    sa.Column('line_moving_4', sa.Boolean(), nullable=False),
    sa.Column('line_moving_5', sa.Boolean(), nullable=False),
    sa.Column('line_moving_6', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reading_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('reading_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    # ### end Alembic commands ###
