"""user_id -> reader_id

Revision ID: cc3ab3512f0a
Revises: f4bbede93e5c
Create Date: 2023-12-08 14:47:59.922039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3ab3512f0a'
down_revision: Union[str, None] = 'f4bbede93e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('reader_id', sa.Integer(), nullable=False))
    op.drop_column('readings', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('readings', 'reader_id')
    # ### end Alembic commands ###
