"""renamed chosen_personal_name to nickname

Revision ID: d81c446fd0b9
Revises: 583d7a32b69d
Create Date: 2024-01-20 21:53:28.091713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81c446fd0b9'
down_revision: Union[str, None] = '583d7a32b69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'chosen_personal_name',
                    new_column_name='nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nickname',
                    new_column_name='chosen_personal_name')
    # ### end Alembic commands ###
