"""clients and readers -> users

Revision ID: d8b7b5cafe09
Revises: cc3ab3512f0a
Create Date: 2023-12-08 20:35:29.874933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8b7b5cafe09'
down_revision: Union[str, None] = 'cc3ab3512f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('personal_name', sa.Text(), nullable=True),
    sa.Column('family_name', sa.Text(), nullable=True),
    sa.Column('chosen_personal_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('pronouns', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('referred_by', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('safe_to_email', sa.Boolean(), nullable=True),
    sa.Column('safe_to_call', sa.Boolean(), nullable=True),
    sa.Column('safe_to_text', sa.Boolean(), nullable=True),
    sa.Column('preferred_contact_method', sa.Text(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('is_reader', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('personal_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('family_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chosen_personal_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pronouns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('referred_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('safe_to_email', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('safe_to_call', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('safe_to_text', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('preferred_contact_method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('safety_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('client_id', name='clients_pkey')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
