"""clients table

Revision ID: f4bbede93e5c
Revises: 84bd18ea4322
Create Date: 2023-12-08 14:44:37.484957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4bbede93e5c'
down_revision: Union[str, None] = '84bd18ea4322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('personal_name', sa.Text(), nullable=True),
    sa.Column('family_name', sa.Text(), nullable=True),
    sa.Column('chosen_personal_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('pronouns', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('referred_by', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('safe_to_email', sa.Boolean(), nullable=True),
    sa.Column('safe_to_call', sa.Boolean(), nullable=True),
    sa.Column('safe_to_text', sa.Boolean(), nullable=True),
    sa.Column('preferred_contact_method', sa.Text(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
