"""reading.py: last_modified to modified_at

Revision ID: fefd33e5c687
Revises: 24069b74b73a
Create Date: 2024-04-11 22:07:33.790553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fefd33e5c687'
down_revision: Union[str, None] = '24069b74b73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.drop_column('readings', 'last_modified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('last_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('readings', 'modified_at')
    # ### end Alembic commands ###
