db.hexagrams.insertMany([
    { "binary": "111111", "king wen": 1, "pinyin": "Qián", "hanzi": "乾", "unicode": "䷀" },
    { "binary": "000000", "king wen": 2, "pinyin": "Kūn", "hanzi": "坤", "unicode": "䷁" },
    { "binary": "100010", "king wen": 3, "pinyin": "Zhūn", "hanzi": "屯", "unicode": "䷂" },
    { "binary": "010001", "king wen": 4, "pinyin": "Méng", "hanzi": "蒙", "unicode": "䷃" },
    { "binary": "111010", "king wen": 5, "pinyin": "Xū", "hanzi": "需", "unicode": "䷄" },
    { "binary": "010111", "king wen": 6, "pinyin": "Sòng", "hanzi": "訟", "unicode": "䷅" },
    { "binary": "010000", "king wen": 7, "pinyin": "Shī", "hanzi": "師", "unicode": "䷆" },
    { "binary": "000010", "king wen": 8, "pinyin": "Bǐ", "hanzi": "比", "unicode": "䷇" },
    { "binary": "111011", "king wen": 9, "pinyin": "Xiǎo Xù", "hanzi": "小畜", "unicode": "䷈" },
    { "binary": "110111", "king wen": 10, "pinyin": "Lǚ", "hanzi": "履", "unicode": "䷉" },
    { "binary": "111000", "king wen": 11, "pinyin": "Tài", "hanzi": "泰", "unicode": "䷊" },
    { "binary": "000111", "king wen": 12, "pinyin": "Pǐ", "hanzi": "否", "unicode": "䷋" },
    { "binary": "101111", "king wen": 13, "pinyin": "Tóng Rén", "hanzi": "同人", "unicode": "䷌" },
    { "binary": "111101", "king wen": 14, "pinyin": "Dà Yǒu", "hanzi": "大有", "unicode": "䷍" },
    { "binary": "001000", "king wen": 15, "pinyin": "Qiān", "hanzi": "謙", "unicode": "䷎" },
    { "binary": "000100", "king wen": 16, "pinyin": "Yù", "hanzi": "豫", "unicode": "䷏" }
], { ordered: false });
db.hexagrams.insertMany([
    { "binary": "100110", "king wen": 17, "pinyin": "Suí", "hanzi": "隨", "unicode": "䷐" },
    { "binary": "011001", "king wen": 18, "pinyin": "Gŭ", "hanzi": "蠱", "unicode": "䷑" },
    { "binary": "110000", "king wen": 19, "pinyin": "Lín", "hanzi": "臨", "unicode": "䷒" },
    { "binary": "000011", "king wen": 20, "pinyin": "Guān", "hanzi": "觀", "unicode": "䷓" },
    { "binary": "100101", "king wen": 21, "pinyin": "Shì Kè", "hanzi": "噬嗑", "unicode": "䷔" },
    { "binary": "101001", "king wen": 22, "pinyin": "Bì", "hanzi": "賁", "unicode": "䷕" },
    { "binary": "000001", "king wen": 23, "pinyin": "Bō", "hanzi": "剝", "unicode": "䷖" },
    { "binary": "100000", "king wen": 24, "pinyin": "Fù", "hanzi": "復", "unicode": "䷗" },
    { "binary": "100111", "king wen": 25, "pinyin": "Wú Wàng", "hanzi": "無妄", "unicode": "䷘" },
    { "binary": "111001", "king wen": 26, "pinyin": "Dà Xù", "hanzi": "大畜", "unicode": "䷙" },
    { "binary": "100001", "king wen": 27, "pinyin": "Yí", "hanzi": "頤", "unicode": "䷚" },
    { "binary": "011110", "king wen": 28, "pinyin": "Dà Guò", "hanzi": "大過", "unicode": "䷛" },
    { "binary": "010010", "king wen": 29, "pinyin": "Kǎn", "hanzi": "坎", "unicode": "䷜" },
    { "binary": "101101", "king wen": 30, "pinyin": "Lí", "hanzi": "離", "unicode": "䷝" },
    { "binary": "001110", "king wen": 31, "pinyin": "Xián", "hanzi": "咸", "unicode": "䷞" },
    { "binary": "011100", "king wen": 32, "pinyin": "Héng", "hanzi": "恆", "unicode": "䷟" },
], { ordered: false });
db.hexagrams.insertMany([
    { "binary": "001111", "king wen": 33, "pinyin": "Dùn", "hanzi": "遯", "unicode": "䷠" },
    { "binary": "111100", "king wen": 34, "pinyin": "Dà Zhuàng", "hanzi": "大壯", "unicode": "䷡" },
    { "binary": "000101", "king wen": 35, "pinyin": "Jìn", "hanzi": "晉", "unicode": "䷢" },
    { "binary": "101000", "king wen": 36, "pinyin": "Míng Yí", "hanzi": "明夷", "unicode": "䷣" },
    { "binary": "101011", "king wen": 37, "pinyin": "Jiā Rén", "hanzi": "家人", "unicode": "䷤" },
    { "binary": "110101", "king wen": 38, "pinyin": "Kuí", "hanzi": "睽", "unicode": "䷥" },
    { "binary": "001010", "king wen": 39, "pinyin": "Jiǎn", "hanzi": "蹇", "unicode": "䷦" },
    { "binary": "010100", "king wen": 40, "pinyin": "Xiè", "hanzi": "解", "unicode": "䷧" },
    { "binary": "110001", "king wen": 41, "pinyin": "Sǔn", "hanzi": "損", "unicode": "䷨" },
    { "binary": "100011", "king wen": 42, "pinyin": "Yì", "hanzi": "益", "unicode": "䷩" },
    { "binary": "111110", "king wen": 43, "pinyin": "Guài", "hanzi": "夬", "unicode": "䷪" },
    { "binary": "011111", "king wen": 44, "pinyin": "Gòu", "hanzi": "姤", "unicode": "䷫" },
    { "binary": "000110", "king wen": 45, "pinyin": "Cuì", "hanzi": "萃", "unicode": "䷬" },
    { "binary": "011000", "king wen": 46, "pinyin": "Shēng", "hanzi": "升", "unicode": "䷭" },
    { "binary": "010110", "king wen": 47, "pinyin": "Kùn", "hanzi": "困", "unicode": "䷮" },
    { "binary": "011010", "king wen": 48, "pinyin": "Jǐng", "hanzi": "井", "unicode": "䷯" },
], { ordered: false });
db.hexagrams.insertMany([
    { "binary": "101110", "king wen": 49, "pinyin": "Gé", "hanzi": "革", "unicode": "䷰" },
    { "binary": "011101", "king wen": 50, "pinyin": "Dǐng", "hanzi": "鼎", "unicode": "䷱" },
    { "binary": "100100", "king wen": 51, "pinyin": "Zhèn", "hanzi": "震", "unicode": "䷲" },
    { "binary": "001001", "king wen": 52, "pinyin": "Gèn", "hanzi": "艮", "unicode": "䷳" },
    { "binary": "001011", "king wen": 53, "pinyin": "Jiàn", "hanzi": "漸", "unicode": "䷴" },
    { "binary": "110100", "king wen": 54, "pinyin": "Guī Mèi", "hanzi": "歸妹", "unicode": "䷵" },
    { "binary": "101100", "king wen": 55, "pinyin": "Fēng", "hanzi": "豐", "unicode": "䷶" },
    { "binary": "001101", "king wen": 56, "pinyin": "Lǚ", "hanzi": "旅", "unicode": "䷷" },
    { "binary": "011011", "king wen": 57, "pinyin": "Xùn", "hanzi": "巽", "unicode": "䷸" },
    { "binary": "110110", "king wen": 58, "pinyin": "Duì", "hanzi": "兌", "unicode": "䷹" },
    { "binary": "010011", "king wen": 59, "pinyin": "Huàn", "hanzi": "渙", "unicode": "䷺" },
    { "binary": "110010", "king wen": 60, "pinyin": "Jié", "hanzi": "節", "unicode": "䷻" },
    { "binary": "110011", "king wen": 61, "pinyin": "Zhōng Fú", "hanzi": "中孚", "unicode": "䷼" },
    { "binary": "001100", "king wen": 62, "pinyin": "Xiǎo Guò", "hanzi": "小過", "unicode": "䷽" },
    { "binary": "101010", "king wen": 63, "pinyin": "Jì Jì", "hanzi": "既濟", "unicode": "䷾" },
    { "binary": "010101", "king wen": 64, "pinyin": "Wèi Jì", "hanzi": "未濟", "unicode": "䷿" },
], { ordered: false });
db.hexagrams.createIndex({ "king wen": 1 });
